### ISSUE TITLE
Support minor upgrades

### ISSUE THREAD

**Issue by magnusuMET** [metno/aerovaldb#69]
Versioning of the crates only uses the patch version, which means every bump is a breaking change. It would be beneficial to use also the minor version so non-breaking changes can be published without requiring all packages to be upgraded in lock-step.

**Comment by thorbjoernl** [comment]
I aim to stabilize the API to keep it more backwards compatible in the future (Probably once #60 ) is merged, but currently since it is early in development each version probably does contain breaking changes :sweat_smile:

**Comment by thorbjoernl** [comment]
Now that #60 has been merged I aim to keep minor version upgrades. As no more action is needed for this issue, I'm closing it.
