### ISSUE TITLE
add maps_overlay entry point

### ISSUE THREAD

**Issue by AugustinMortier** [metno/aerovaldb#81]
Needed: new entry point to get png path (similar to report images).

- proposed API entry point: `maps_overlays/{project}/{experiment}/{obsmod}/{variable}/{date}`
- file location: `project/experiment/contour/overlay/{obsmod}_{variable}_{date}.png`

`obsmod` being the source (can be either a model or an observation network)

We might need a more general *wms* entry point with a zoom level parameter, but this entry point will allow users to test the new png maps feature in the meatime.

# Context
- https://github.com/metno/AeroToolsIssues/issues/5#issuecomment-2312462405

**Comment by AugustinMortier** [comment]
see api: [MR25](https://gitlab.met.no/aeroval/api/-/merge_requests/25)

**Comment by thorbjoernl** [comment]
After discussion with @heikoklein, this should be extended to provide two endpoints:

`get_image_layer()` - Returns json with information about the images? Need specification about what information it should contain.

`get_map_overlay()` - The existing endpoint for fetching the images. Route should include extra information about zoom, x, y, metadata (?)

eg. `/maps_overlays/{project}/{experiment}/{obsmod}/{variable}/{date}/{zoom}/{x}/{y}` with file path `/project/experiment/contour/overlay/{obsmod}_{variable}_{date}_{zoom}_{x}_{y}.png`

**Comment by AugustinMortier** [comment]
In the current working version (*overlays*, but nor *wms*), I have just completed the maps info available in the config file.
So, pyaerocom should just write in those info into the cfg file.


```
    "modelmaps_opts": {
        "maps_res_deg": 5,
        "type": "overlay",
        "boundaries": {
            "west": -50.0,
            "east": 90.0,
            "south": 25.0,
            "north": 85.0
        },
        "color_scale": {
            "vcdno2": {
                "levels": [
                    0,
                    5,
                    10,
                    15,
                    20,
                    25,
                    30,
                    35,
                    40,
                    45,
                    50
                ],
                "color_map": "coolwarm",
                "units": "ppb"
            }
        }
 ```

**Comment by AugustinMortier** [comment]
I would say the *wms* solution with different zoom levels support should be a different issue. It's not ready on pyaerocom yet..
